/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CameraControls: typeof import('./src/components/CameraControls.vue')['default']
    DetectionResults: typeof import('./src/components/DetectionResults.vue')['default']
    HeaderComponent: typeof import('./src/components/_base/HeaderComponent.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ImageCapture: typeof import('./src/components/ImageCapture.vue')['default']
    ModeSwitch: typeof import('./src/components/ModeSwitch.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RouterViewTransition: typeof import('./src/components/_base/RouterViewTransition.vue')['default']
    Vision: typeof import('./src/components/Vision.vue')['default']
  }
}
